name: Validate Plugins

on:
  pull_request:
    paths:
      - 'plugins/**'
      - '.claude-plugin/**'
  push:
    branches:
      - main
    paths:
      - 'plugins/**'
      - '.claude-plugin/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude Code CLI
        run: |
          npm install -g @anthropic-ai/claude-code

      - name: Validate TDD Workflow Plugin
        run: |
          claude plugin validate plugins/tdd-workflow-plugin

      - name: Validate Docs Plugin
        run: |
          claude plugin validate plugins/docs-plugin

      - name: Validate GitHub Flow Plugin
        run: |
          claude plugin validate plugins/github-flow-plugin

      - name: Validate Quality Guardian Plugin
        run: |
          claude plugin validate plugins/quality-guardian-plugin

      - name: Validate Skill Generator Plugin
        run: |
          claude plugin validate plugins/skill-generator-plugin

      - name: Validate Novel Writer Plugin
        run: |
          claude plugin validate plugins/novel-writer-plugin

      - name: Validate Marketplace Manifest
        run: |
          if [ ! -f ".claude-plugin/marketplace.json" ]; then
            echo "Error: marketplace.json not found"
            exit 1
          fi

          # JSON 형식 검증
          cat .claude-plugin/marketplace.json | jq empty

      - name: Check Plugin Documentation
        run: |
          # 각 플러그인에 README.md가 있는지 확인
          for plugin_dir in plugins/*-plugin; do
            if [ -d "$plugin_dir" ]; then
              if [ ! -f "$plugin_dir/README.md" ]; then
                echo "Error: README.md not found in $plugin_dir"
                exit 1
              fi
              echo "✓ README.md found in $plugin_dir"
            fi
          done

      - name: Summary
        if: success()
        run: |
          echo "✅ All plugins validated successfully!"
          echo "✅ Marketplace manifest is valid"
          echo "✅ All plugin documentation is present"
